version: '3.8'

services:
  legal-rag:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - LOG_LEVEL=INFO
      - USE_GPU=true
    depends_on:
      - milvus
      - chroma
      - redis

  milvus:
    image: milvusdb/milvus:v2.4.2
    ports:
      - "19530:19530"
    volumes:
      - milvus_data:/var/lib/milvus
    environment:
      - ETCD_ENDPOINTS=http://etcd:2379
      - MINIO_ENDPOINT=minio:9000
    depends_on:
      - etcd
      - minio

  #etcd
  etcd:
    image: quay.io/coreos/etcd:v3.5.10
    environment:
      - ETCD_AUTO_COMPACTION_MODE = "revision"
      - ETCD_AUTO_COMPACTION_RETENTION = "1000"
      - ETCD_QUOTA_BACKEND_BYTES = "4294967296"
    volumes:
      - etcd_data:/etcd 

  #minio
  minio:
    image: minio/minio:RELEASE.2025-06-24T18-44-10Z
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  #chroma
  chroma:
    image: chromadb/chroma:v2.4.2
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  milvus_data:
  chroma_data:
  redis_data:
  etcd_data:
  minio_data:
      